name: shared
description: Common and shared code
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.2

dependencies:
  env:
    path: "../env"
  flutter:
    sdk: flutter
  intl: ^0.19.0
  logger: ^2.4.0
  powersync: ^1.2.2


dev_dependencies:
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
