name: powersync_repository
description: Repository for PowerSync
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: "^3.22.2"

dependencies:
  env:
    path: "../env"
  flutter:
    sdk: flutter
  path: ">=1.8.3 <=1.9.0"
  path_provider: ^2.1.2
  powersync: ^1.2.2
  shared:
    path: "../shared"
  supabase_flutter: ^2.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
