name: repository
description: Instaclone repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  auth_client:
    path: "../auth_client/auth_client"
  database_client:
    path: "../database_client"
  powersync_repository:
    path: "../powersync_repository"
  rxdart: ^0.27.7

dev_dependencies:
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
