name: supabase_auth_client
description: Supabase auth client implementation
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  auth_client:
    path: "../auth_client"
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  powersync_repository:
    path: "../../powersync_repository"
  supabase_flutter: ^2.5.11
  token_storage:
    path: "../token_storage"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
