name: database_client
description: Database client repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.2

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.2
  very_good_analysis: ^6.0.0

dependencies:
  dio: ^5.5.0+1
  env:
    path: "../env"
  flutter:
    sdk: flutter
  powersync_repository:
    path: "../powersync_repository"
  repository: 
    path: "../repository"
  shared:
    path: "../shared"
  
